### ISSUE TITLE
[P5][App] App.js 내 TodoTemplate를 별도 컴포넌트로 나누면 어떨까요?

### ISSUE THREAD

**Issue by yeppin** [snulion10thReactSeminar/todolist#11]
`TodoTemplate.js`를 별도로 만들고 `App.js` 에서 합성하면
부모 컴포넌트 - 자식 컴포넌트의 관계를 10기들에게 가장 깔끔하게 보여줄 수 있을 것 같습니다!
더해서, 로그인/로그아웃 기능이 추가되는 등의 작업이 생긴다면 현 TodoTemplate과 동등한 레벨의 Account 컴포넌트가 생길 수도 있을 것 같아
가능하다면 미리 나눠두는 것도 방법이라고 생각합니다!🥳
https://github.com/snulion10thReactSeminar/todolist/blob/3acd792e00b410a0c96ed36d87afdd912249514e/src/App.js#L28-L37

**Comment by jaehvvan** [comment]
이거 반영하면서, App.js 에 있는 함수와 상태도 같이 옮겨주세요.
