### ISSUE TITLE
[P4] [TodoCreate] 공백 케이스 핸들링

### ISSUE THREAD

**Issue by lerrybe** [snulion10thReactSeminar/todolist#12]
https://github.com/snulion10thReactSeminar/todolist/blob/3acd792e00b410a0c96ed36d87afdd912249514e/src/components/TodoCreate/index.js#L9-L14

넘 사소한 부분이지만
현재 공백 시에도 todo가 추가되는 것 같아서, 관련된 부분 핸들링 해주는 건 어떨까요?!

```javascript
  const onSubmit = (e) => {
    e.preventDefault();
    if (!text) {
      // alert 후 return 혹은 그냥 return 
      alert('할 일을 입력해주세요!');
      return;
    }
    onCreate(text);
    ...
  };
```

**Comment by kjw7953** [comment]
오호 근데 이거 `!text`에 공백이 안걸리지 않나요?!

trim 등을 사용해서 text의 공백을 제거한 뒤에 조건문으로 검사하면 좋을 것 같아요!
```
if (!text.trim()) {
  ...
  return;
}
```

**Comment by kjw7953** [comment]
아 공백입력 == '스페이스 같은 공백으로 이루어진 문자열'이라고 생각했습니다ㅋㅋㅋㅋ 빈문자열인 경우에 처리하는 아이디어도 좋습니다! 왓에버..!

**Comment by jaehvvan** [comment]
반영해주세요.
