### ISSUE TITLE
[TodoItem] 불분명한 변수명 및 className 리팩토링 (ex. isShowRemove, className remove 등등)

### ISSUE THREAD

**Issue by lynn0506** [snulion10thReactSeminar/todolist#6]
**`isShowRemove`** 의 경우 Is랑 show 동사가 두개이고, Remove가 무엇인지 조금 헷갈리는 것 같습니다. 
의미를 좀 더 분명히 하면 좋을 것 같아요! ( `isRemoveIconVisible` 정도로 생각해봤는데, 더 좋은 변수명 있으면 추천해주세욧!) 

https://github.com/snulion10thReactSeminar/todolist/blob/3acd792e00b410a0c96ed36d87afdd912249514e/src/components/TodoItem/index.js#L5-L13

넘 사소하지만,,, ClassName을 그냥 **remove**라고 하기보다는 `remove-icon` 등으로 명사형태로 어떤 의미인지 분명히 드러날 수 있게 naming을 하면 코드를 읽는 개발자가 더 이해하기 쉬울 것 같습니다. 

https://github.com/snulion10thReactSeminar/todolist/blob/3acd792e00b410a0c96ed36d87afdd912249514e/src/components/TodoItem/index.js#L21-L28

**Comment by jaehvvan** [comment]
상태 명 변경은 꼭 반영해주세요.
클래스명은 선택적으로 반영해주세요.
