### ISSUE TITLE
[App] spread 문법을 활용하는 것은 어떤가요!

### ISSUE THREAD

**Issue by lynn0506** [snulion10thReactSeminar/todolist#7]
https://github.com/snulion10thReactSeminar/todolist/blob/3acd792e00b410a0c96ed36d87afdd912249514e/src/App.js#L13-L18

넘 사소하지만 spread 문법을 활용하면, state 관리 시 훨 간단하기에 적어보았습니닷...

``` javascript 
     todo.id === id ? { ...todo, done: !todo.done } : todo 
```

**Comment by jaehvvan** [comment]
반영해주세요.
